(feat) NFT Command (#6)
* feat: :construction: Initialize NFT Command

This provides basic scaffolding over whether or not the message is a reply or not

* Create dependabot.yml

* ci: :construction_worker: Run `pr-image-build-scan` on dependabot PR

* feat(bot): Add `Message Type` output

* ci: :construction_worker: Run `pr-image-build-scan` on dependabot PRs

so I can know if my images are building or nah

* chore(deps): :arrow_up: Run `yarn upgrade` (#12)

I don't even know if my code will work LOL. Going to use `renovate` soon probably

* Configure Renovate (#13)

* chore(deps): add renovate.json

* chore(deps): add renovate.json

* ci: update `Renovate.json`

Co-authored-by: Renovate Bot <bot@renovateapp.com>
Co-authored-by: Joshua Ji <joshua.ji@jiwhiz.com>

* ci: Add `schedule` option to renovate

REnovates not during work hours, as if I am a working developer kek

* fix(deps): pin dependencies (#14)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

* chore(deps): update appleboy/ssh-action commit hash to 1a8b378 (#15)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

* ci: :fire: Delete `dependabot.yml` in favor of `renovate`

* chore(deps): Batch all minoe devDependencies in one PR

Based off of this: https://docs.renovatebot.com/configuration-options/#groupname

* chore(deps): update burnett01/rsync-deployments action to v5.2 (#24)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

* fix(deps): update dependency js-yaml to v4 (#23)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

* fix(deps): update dependency discord-api-types to ^0.26.0 (#17)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

* chore(deps): :heavy_minus_sign: Change up dependencies (#25)

Remove `fs` (it should be in node), move typescript to devDep (why wasn't it there in the first place?!)

* ci: :construction_worker: Create `tests.yml`

* Add Tests for `apps/server` (#27)

* chore(deps): :heavy_plus_sign: Add testing deps

* refactor(server): :art: Split `index.ts` into `app.ts` and `index.ts`

This is for easier testing

* Also return `200` status for `mainRoute`

* test(rootRoute): :white_check_mark: Test that root route returns status `200`

* ci: :construction_worker: Add CI test scripts

* ci: :green_heart: Install deps

Cannot believe I forgot that lmao

* ci: :green_heart: Fix node versions, add note on README

Forgot discord.js is incompatible with node `16.6` and below

* ci: :construction_worker: Only test on a single node v16

Too many tests clog up the system lol

* feat: :construction: Initialize NFT Command

This provides basic scaffolding over whether or not the message is a reply or not

* feat(bot): Add `Message Type` output

* chore(deps): pin dependencies (#26)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

* chore(deps): pin dependency @types/jest to 27.4.0 (#29)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

* chore: Renovate bot: Add `dependencies` label

* chore(deps): update dependency eslint to v8 (#20)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

* chore(deps): update typescript-eslint monorepo to v5 (#21)

Co-authored-by: Renovate Bot <bot@renovateapp.com>

* feat: :construction: Initialize NFT Command

This provides basic scaffolding over whether or not the message is a reply or not

* feat(bot): Add `Message Type` output

* feat: :label: Add NFT type

i feel unpure unironically typing "nft"

* feat: Add `supabase` folder for possible Github Actions with Supabase

* ci: :construction_worker: Add Action to test out Supabase locally

* ci: :green_heart: Fix supabase CI test action

* ci: :green_heart: CI SUCKS

* ci: :green_heart: Run supabase init

* More supabase ci stuff...

* Add supabase migration
This should fix the CI errors but idk

* Apparently the action is failing because...
Error: Failed to connect to Docker daemon. Is Docker running?

* Hacking together stuff so Docker can work on MacOS
It is not supported and never will be smodge
https://github.community/t/why-is-docker-not-installed-on-macos/17017/7

* Use ubuntu for supabase test
BREW IS INSTALLED ON LINUX SHEEEEE

* supabase can't connect to the remote db so wahtever

* `can't open /dev/tty` error - DEBUG

* feat(bot): :construction: NFT command coming along

OH YEAH!

* feat(bot): :sparkles: Add support for stickers

* chore: :fire: Deleting supabase test CI

it's not working lol

* test(server): :truck: Move test case stuff

* feat(bot): :sparkles: NFT command is coming along more

Creates but does not upload the NFT

* test(bot): :heavy_plus_sign: Add test deps

I'm not even doing tests lol jest is so confusing

* fix(bot): :bug: Fix failing docker build cmd

tsconfig was complaining that `jest.config.ts` was not in the `rootDir` thing, fixed promptly

* feat(server): :sparkles: Add typesafe `parseBody` middleware with `io-ts`

With tests!

* test(server): :white_check_mark: Add `/trevimg` tests
But the tests are too slow :((

* test(server): Fix import (fixes test)

* refactor(server): :recycle: Update routing exports

* feat(server): :sparkles: `parseQuery` middleware

* refactor(server): :recycle: Use `parseQuery` middleware (instead of type inference)

Also change up the tests a bit

* Fix `trev` type stuff

I can finally use `const` now that the Query is typed

* feat(server): NFT Upload works!

Very bad error messages though...

* fix: :card_file_box: `createdAt` no longer has default, it is created on the server

* refactor(bot): :recycle: Update command file structure

imports are one level deep now

* refactor(bot): :recycle: Split the NFT code into chunks

* refactor(bot): :fire: Delete selectMenus

* test(bot): :white_check_mark: Tests for `nft` command

* test(bot): :white_check_mark: `getNFTType` tests

* ci: :construction_worker: Also run Bot tests

* feat(bot): :goal_net: Better error handling

* style(bot): :bulb: Add comment about `createNFT.ts`

* feat(bot): `.nft list` command

Co-authored-by: LeCitrus <LeCitrus@users.noreply.github.com>

* build(deps): :heavy_plus_sign: Add `axios` to custom-types

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>
Co-authored-by: Renovate Bot <bot@renovateapp.com>
Co-authored-by: LeCitrus <LeCitrus@users.noreply.github.com>